#!/bin/bash
# This is just a simple script that installs all of the standard
# stuff that I always want on a newly installed linux OS and
# calls some other scripts that configure my links and apps...
set -u
set -e

#Duck-typing: try apt-get and if it works use it...
if $(which apt-get &> /dev/null); then
	sudo apt-get update
	sudo apt-get dist-upgrade

	sudo apt-get install git
	sudo apt-get install vim-gtk
	sudo apt-get install zsh
	sudo apt-get install htop

	sudo apt-get install python-numpy python-scipy ipython python-matplotlib

	#Allow installation of numpy and scipy and matplotlib with pip
	sudo apt-get build-dep python-matplotlib python-scipy python-numpy

	#allow installation of pyodbc
	sudo apt-get install unixodbc-dev

elif $(which dnf &> /dev/null); then
	sudo dnf update

	sudo dnf group install 'C Development Tools and Libraries'
	sudo dnf group install 'Development Tools'
	sudo dnf install vim-enhanced vim-X11
	sudo dnf install zsh
	sudo dnf install htop

	sudo dnf install numpy scipy ipython python-matplotlib
	sudo dnf builddep python-matplotlib numpy scipy

	#allow installation of pyodbc
	sudo dnf install unixODBC-devel

elif $(which yum &> /dev/null); then
	sudo yum update

	sudo yum group install 'C Development Tools and Libraries'
	sudo yum group install 'Development Tools'
	sudo yum install vim-enhanced vim-X11
	sudo yum install zsh
	sudo yum install htop

	sudo yum install numpy scipy ipython python-matplotlib
	sudo yum-builddep python-matplotlib numpy scipy

	#allow installation of pyodbc
	sudo yum install unixODBC-devel
fi

sudo chsh -s $(which zsh) $USER

# Grab my repo in case it's not already there.
mkdir -p ~/usr
pushd ~/usr

if [ ! -d muiltools ]; then
	echo "Going to clone muiltools from GitHub now. You will be prompted for a password if you don't have your SSH key from this machine in GitHub (you can do that now if you want)... press enter when you're ready... (ctrl-c to quit)"
	read
	git clone git@github.com:robertmuil/muiltools.git
	pushd muiltools && git submodule init && git submodule update
else
	pushd muiltools
	git pull
fi

#Configure backup on new machine
./configure_backup

#Run the setup program to establish links to personal config
./link_dotfiles

#TODO: do we want to setup a standard Python virtualenv?

popd
popd
