#!/bin/bash

#This is a simple script intended to fetch all external command-line tools I like to have installed.
# This is used only for those that don't have git-accessible repositories, because those will be
# handled as sub-modules
#

EXT_DIR='externals'

if [ ! -d "$EXT_DIR" ]; then
	mkdir -v -p "$EXT_DIR"
fi

pushd $EXT_DIR
#First is oodiff.
curl http://www-verimag.imag.fr/~moy/opendocument/oodiff > oodiff

#Second is ibam... 
curl http://prdownloads.sourceforge.net/ibam/ibam-0.5.2.tar.gz > ibam-0.5.2.tar.gz
tar -xzvf ibam-*.tgz
patch ibam.inl.*.patch

#Third is shell-scripting recipes
curl `cat ssr-scripts.url` > ssr-scripts.tar.gz
tar -xzvf ssr-scripts.tar.gz

popd
