#!/bin/bash

#This is a simple script intended to fetch all external command-line tools I like to have installed.
# This is used only for those that don't have git-accessible repositories, because those will be
# handled as sub-modules
#

EXT_DIR='externals'

if [ ! -d "$EXT_DIR" ]; then
	mkdir -v -p "$EXT_DIR"
fi

#First is oodiff.
curl http://www-verimag.imag.fr/~moy/opendocument/oodiff > "$EXT_DIR"/oodiff
